<? $account = $this->auth()->getManager(); ?>
<div class="banner container">
	<div class="header-menu">
		<ul id="nav-list">
      <li id="aboup"  class="oneline"><a href="/">Home</a></li>
      <li id="abouc"  class="oneline"><a href="http://www.catholicresearch.net/cms/index.php/about-crra/">About</a></li>
      <li id="lead"   class="twoline"><a href="http://www.catholicresearch.net/cms/index.php/the-catholic-portal/">Catholic Portal</a></li>
      <li id="papers" class="threeline"><a href="http://www.catholicresearch.net/cms/index.php/catholic-newspapers-program/">Catholic Newspapers Program</a></li>
      <li id="logi"   class="twoline"><a href="http://www.catholicresearch.net/cms/index.php/resources/">Links&nbsp;&amp; Resources</a></li>
      <li id="part"   class="oneline"><a href="http://www.catholicresearch.net/cms/index.php/crra-news-and-events/">What's&nbsp;New</a></li>
      <li id="port"   class="oneline"><a href="http://www.catholicresearch.net/cms/index.php/join/">Membership</a></li>
    </ul>
	</div>
</div>

<div class="navbar container">
  <? if ($this->layout()->searchbox !== false): ?>
    <?=$this->layout()->searchbox ?>
  <? endif; ?>
  <? if (!isset($this->layout()->renderingError)): ?>
    <nav>
      <ul role="navigation" class="nav navbar-nav navbar-right flip">
        <? if ($this->feedback()->tabEnabled()): ?>
          <li>
            <a id="feedbackLink" data-lightbox href="<?=$this->url('feedback-home') ?>"><i class="fa fa-envelope"></i> <?=$this->transEsc("Feedback")?></a>
          </li>
        <? endif; ?>
        <? $cart = $this->cart(); if ($cart->isActive()): ?>
          <li id="cartSummary">
            <a id="cartItems" data-lightbox title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>"><i class="fa fa-suitcase"></i> <strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?><?=$cart->isFull() ? ' (' .  $this->transEsc('bookbag_full') . ')' : ''?></a>
          </li>
        <? endif; ?>
        <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
          <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
            <a href="<?=$this->url('myresearch-home', array(), array('query' => array('redirect' => 0)))?>"><i class="fa fa-home"></i> <?=$this->transEsc("Your Account")?></a>
          </li>
          <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
            <a href="<?=$this->url('myresearch-logout')?>" class="logout"><i class="fa fa-sign-out"></i> <?=$this->transEsc("Log Out")?></a>
          </li>
          <li id="loginOptions"<? if($account->isLoggedIn()): ?> class="hidden"<? endif ?>>
            <? if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
              <a href="<?=$this->url('myresearch-userlogin')?>"><i class="fa fa-sign-in"></i> <?=$this->transEsc("Institutional Login")?></a>
            <? else: ?>
              <a href="<?=$this->url('myresearch-userlogin')?>" data-lightbox><i class="fa fa-sign-in"></i> <?=$this->transEsc("Login")?></a>
            <? endif; ?>
          </li>
        <? endif; ?>

        <? if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
          <li class="theme dropdown">
            <form method="post" name="themeForm" id="themeForm">
              <input type="hidden" name="ui"/>
            </form>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <? foreach ($this->layout()->themeOptions as $current): ?>
                <li<?=$current['selected'] ? ' class="active"' : ''?>><a href="#" onClick="document.themeForm.ui.value='<?=$this->escapeHtmlAttr($current['name'])?>';document.themeForm.submit()"><?=$this->transEsc($current['desc'])?></a></li>
              <? endforeach; ?>
            </ul>
          </li>
        <? endif; ?>

        <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
          <li class="language dropdown">
            <form method="post" name="langForm" id="langForm">
              <input type="hidden" name="mylang"/>
            </form>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Language")?> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>><a href="#" onClick="document.langForm.mylang.value='<?=$langCode?>';document.langForm.submit()"><?=$this->displayLanguageOption($langName)?></a></li>
              <? endforeach; ?>
            </ul>
          </li>
        <? endif; ?>
      </ul>
    </nav>
  <? endif; ?>
</div>
