
<p style='text-align: center'><a href="<a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></p>
<p style='text-align: center'><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></p>
<p style='text-align: center'><a href="mailto:plawton@nd.edu">Contact us</a></p>
<p style='text-align: center'><a href="http://www.catholicresearch.net/blog/">CRRA Blog</a></p>
<div class="clear"></div>
