<? $account = $this->auth()->getManager(); ?>
<!-- We should hide the top search bar and breadcrumbs in some contexts: -->
<div>
<img src= "/vufind/themes/crra/images/header.png" style='margin-bottom: 1em' />
	<div style='margin-top: -45px; margin-bottom: 45px; margin-left: 87px' class="header-menu">
		<ul id="nav-list">
            <li id="aboup"><a href="/">Home</a></li>
            <li id="abouc"><a href="http://www.catholicresearch.net/cms/index.php/about-crra/">About</a></li>

            <li id="lead"><a href="http://www.catholicresearch.net/cms/index.php/the-catholic-portal/">Catholic</br>Portal</a></li>
            <li id="papers"><a href="http://www.catholicresearch.net/cms/index.php/catholic-newspapers-program/">Catholic</br>Newspapers<br>Program</a></li>
            <li id="logi"><a href="http://www.catholicresearch.net/cms/index.php/resources/">Links &amp; <br />Resources</a></li>
            <li id="part"><a href="http://www.catholicresearch.net/cms/index.php/crra-news-and-events/">What's<br>New</a></li>
            <li id="port"><a href="http://www.catholicresearch.net/cms/index.php/join/">Membership</a></li>
        </ul>
	</div>
</div>

<? if (!isset($this->layout()->renderingError)): ?>
  <div id="headerRight">
    <? $cart = $this->cart(); if ($cart->isActive()): ?>
      <div id="cartSummary" class="cartSummary">
        <a id="cartItems" title="<?=$this->transEsc('View Book Bag')?>" class="bookbag" href="<?=$this->url('cart-home')?>"><strong><span><?=count($cart->getItems())?></span></strong> <?=$this->transEsc('items')?> <?=$cart->isFull() ? '(' .  $this->transEsc('bookbag_full') . ')' : ''?></a>
        <a id="viewCart" title="<?=$this->transEsc('View Book Bag')?>" class="viewCart bookbag offscreen" href="<?=$this->url('cart-home')?>"><strong><span id="cartSize"><?=count($cart->getItems())?></span></strong> <?=$this->transEsc('items')?><span id="cartStatus"><?=$cart->isFull() ? $this->transEsc('bookbag_full') : '&nbsp;'?></span></a>
      </div>
    <? endif; ?>
    <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
      <div id="logoutOptions"<?=!$account->isLoggedIn() ? ' class="hide"' : ''?>>
        <a class="account" href="<?=$this->url('myresearch-home', array(), array('query' => array('redirect' => 0)))?>"><?=$this->transEsc("Your Account")?></a> |
		<a class="logout" href="<?=$this->url('myresearch-logout')?>"><?=$this->transEsc("Log Out")?></a>
      </div>
	  <div id="loginOptions"<?=$account->isLoggedIn() ? ' class="hide"' : ''?>>
      <? if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-userlogin')))): ?>
        <a class="login" href="<?=$this->url('myresearch-userlogin')?>"><?=$this->transEsc("Institutional Login")?></a>
      <? else: ?>
        <a class="login" href="<?=$this->url('myresearch-userlogin')?>"><?=$this->transEsc("Login")?></a>
      <? endif; ?>
      </div>
    <? endif; ?>
    <? if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
    <form method="post" name="themeForm" action="" id="themeForm">
      <label for="themeForm_ui"><?=$this->transEsc("Theme")?>:</label>
      <select id="themeForm_ui" name="ui" class="jumpMenu">
      <? foreach ($this->layout()->themeOptions as $current): ?>
        <option value="<?=$this->escapeHtmlAttr($current['name'])?>"<?=$current['selected'] ? ' selected="selected"' : ''?>><?=$this->transEsc($current['desc'])?></option>
      <? endforeach; ?>
      </select>
      <noscript><input type="submit" value="<?=$this->transEsc("Set")?>" /></noscript>
    </form>
    <? endif; ?>
    <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
    <form method="post" name="langForm" action="" id="langForm">
      <label for="langForm_mylang"><?=$this->transEsc("Language")?>:</label>
      <select id="langForm_mylang" name="mylang" class="jumpMenu">
      <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
        <option value="<?=$langCode?>"<?=$this->layout()->userLang == $langCode ? ' selected="selected"' : ''?>><?=$this->displayLanguageOption($langName)?></option>
      <? endforeach; ?>
      </select>
      <noscript><input type="submit" value="<?=$this->transEsc("Set")?>" /></noscript>
    </form>
    <? endif; ?>
  </div>
<? endif; ?>

<!-- Move the Search Form near the top of the page -->
<? if (!isset($this->layout()->searchbox)) {
             $this->layout()->searchbox = $this->render('search/searchbox.phtml');
         }
?>
<? if ($this->layout()->searchbox !== false): ?>
      <div class="searchbox">
        <?=$this->layout()->searchbox?>
      </div>
<? endif; ?>

<div class="clear"></div>
