<?
    // Set page title.
    $this->headTitle($this->translate('Search Home'));

    // Disable top search box -- this page has a special layout.
    $this->layout()->searchbox = false;

    // Set default value if necessary:
    if (!isset($this->searchClassId)) {
        $this->searchClassId = 'Solr';
    }

    // Load search actions and settings (if any):
    $options = $this->searchOptions($this->searchClassId);
    $basicSearch = $options->getSearchAction();
    $advSearch = $options->getAdvancedSearchAction();
?>
<div class="searchHomeContent">
  <? if ($this->ils()->getOfflineMode() == "ils-offline"): ?>
    <div class="sysInfo">
      <h2><?=$this->transEsc('ils_offline_title')?></h2>
      <p><strong><?=$this->transEsc('ils_offline_status')?></strong></p>
      <p><?=$this->transEsc('ils_offline_home_message')?></p>
      <? $supportEmail = $this->escapeHtml($this->systemEmail()); ?>
      <p><a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a></p>
    </div>
  <? endif; ?>
  <div class="searchHomeForm">
    <?=$this->render("search/searchbox.phtml")?>
  </div>
</div>

<div>
	<h1>Welcome to the Catholic Research Resources Alliance (CRRA)</h1>

	<p>The CRRA is a collaborative effort initiated by eight Catholic colleges and universities to share their resources electronically with librarians, archivists, researchers, scholars, and the general public, all who are interested in the Catholic experience. The mission of the CRRA is to provide enduring global access to Catholic research resources. Our immediate focus is creating access to those rare, unique and uncommon research materials relating to every aspect of the Catholic experience, which are held by college, university, and seminary libraries and archives in North America.</p>
	
	<h2>About the Catholic Portal</h2>
	
	<p>The Catholic Research Resources Portal, or "Catholic Portal," provides access to rare, unique and/or uncommon materials in libraries, seminaries, special collections and archives. By electronically bringing together resources in many formats from many collections, the Portal enables easy, effective and global discovery of Catholic research resources.</p>
	
	<p>To <a href="./Search/Results?lookfor=&type=AllFields&submit=Find">BROWSE</a> all records currently in the Portal, simply click on the "Find" button above. </p>

</div>