<?
  // Set page title.
  $this->headTitle($this->translate('Email this Search'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li> ') .
    '<li class="active">' . $this->transEsc('Email this Search') . '</li>';
?>
<h2><?=$this->transEsc('Email this Search') ?></h2>
<?=$this->flashmessages()?>
<form class="form-horizontal" method="post"  name="emailSearch">
  <input type="hidden" name="url" value="<?=$this->escapeHtmlAttr($this->url)?>" />
  <div class="form-group">
    <label class="col-sm-3 control-label" for="email_to"><?=$this->transEsc('To (email address - required)')?>:</label>
    <div class="col-sm-9">
      <input type="email" id="email_to" class="form-control" oninvalid="$('#modal .fa-spinner').remove()" name="to" value="<?=isset($this->to) ? $this->to : ''?>" required />
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label" for="email_from"><?=$this->transEsc('From (email address - required)')?>:</label>
    <div class="col-sm-9">
      <input type="email" id="email_from" oninvalid="$('#modal .fa-spinner').remove()" name="from" value="<?=isset($this->from) ? $this->from : ''?>" size="40" class="form-control" required />
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label" for="email_message"><?=$this->transEsc('Message')?>:</label>
    <div class="col-sm-9">
      <textarea id="email_message" class="form-control" name="message" rows="4"><?=isset($this->message) ? $this->message : ''?></textarea>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-9 col-sm-offset-3">
      <input type="submit" class="btn btn-primary" name="submit" value="<?=$this->transEsc('Send')?>"/>
    </div>
  </div>
</form>
